MehrCodeLandV1/Areas/Admin/Controllers/AdminHomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MehrCodeLandV1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminHomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MehrCodeLandV1/Areas/UserPannel/Controllers/UserPannelHomeController.cs
using Core.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MehrCodeLandV1.Areas.UserPannel.Controllers
{
    [Area("UserPannel")]
    public class UserPannelHomeController : Controller
    {
        private readonly IUserService _userService;
        public UserPannelHomeController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View(_userService.GetUserInformations(User.Identity.Name)); 
        }
    }
}

MehrCodeLandV1/Areas/Users/Controllers/UserHomeController.cs
using Core.Convertor;
using Core.DTOs;
using Core.Generator;
using Core.Security;
using Core.Sender;
using Core.Service.Interfaces;
using Data.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Security.Claims;
using static Core.Convertor.ViewToString;

namespace MehrCodeLandV1.Areas.Users.Controllers
{
    [Area("Users")]
    public class UserHomeController : Controller
    {
        private readonly IUserService _userService;
        private readonly IViewRenderService _render;
        public UserHomeController(IUserService userService , IViewRenderService render )
        {
            _userService = userService;
            _render = render;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Hello()
        {
            return View();
        }

        #region SignUp

        [Route("SignUp")]
        public IActionResult SignUp()
        {
            return View();
        }

        [Route("SignUp")]
        [HttpPost]
        public IActionResult SignUp( SignUpViewModel signUp )
        {
            if (!ModelState.IsValid)
            {
                return View(signUp);
            }
            if (_userService.IsEmail(FixText.FixTexts(signUp.Email)))
            {
                ModelState.AddModelError("Email", "Is Exist!");
                return View(signUp);
            }
            if (_userService.IsUsername(FixText.FixTexts(signUp.Usernmae)))
            {
                ModelState.AddModelError("Username", "Is Exist");
                return View(signUp);
            }

            User user = new User()
            {
                Username = signUp.Usernmae,
                Password = PasswordHashC.EncodePasswordMd5(signUp.Password),
                IsActive = false,
                ActiveCode = ActiveCodeGen.GenerateCode(),
                Email = signUp.Email,
                ImgUrl = "",
                Created = DateTime.Now,
            };
            _userService.Add(user);

            #region EmailSenders

            string Body = _render.RenderToStringAsync("Register", user);
            EmailSenders.Send(user.Email, "Register", Body);

            #endregion
            return View();
        }

        #endregion


        #region SignIn

        [Route("SignIn")]
        public IActionResult SignIn()
        {
            return View();
        }

        [Route("SignIn")]
        [HttpPost]
        public IActionResult SignIn(SignInViewModel signIn)
        {
            if (!ModelState.IsValid)
            {
                return View(signIn);
            }


            var user = _userService.LoginUser(signIn);
            if(user != null)
            {
                if (user.IsActive)
                {
                    var claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                        new Claim(ClaimTypes.Name , user.Username),
                    };
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);

                    var properties = new AuthenticationProperties()
                    {
                        IsPersistent = signIn.RememberMe
                    };
                    HttpContext.SignInAsync(principal, properties);

                    ViewBag.IsSuccess = true;
                    return View();
                }
                else
                {
                    ModelState.AddModelError("Eamil", "Your Email Address Is Not Active");
                }
            }

            ModelState.AddModelError("Eamil", "Email Not Found Or Password Incorect");
            return View();
        }



        #endregion


        #region Email Active

        public IActionResult ActiveUser(string id)
        {
            ViewBag.IsActived  =  _userService.ActiveAccount(id);
            return View();
        }

        #endregion


        #region Forgot Password

        [Route("ForgotPassword")]
        public IActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        [Route("ForgotPassword")]
        public IActionResult ForgotPassword(ForgotPasswordVm forgot )
        {
            if (!ModelState.IsValid)
            {
                return View(forgot);
            }

            forgot.Email = FixText.FixTexts(forgot.Email);
            User user = _userService.GetUserByEmail(forgot);
            if(user == null)
            {
                ModelState.AddModelError("Email", "Email Not Found !");
                return View(forgot);

            }

            string Body = _render.RenderToStringAsync("ForgotView", user);
            EmailSenders.Send(user.Email, "Forgot!", Body);
            ViewBag.IsSuccess = true;

            return View();

        }

        #endregion

        #region Reset Password

        public IActionResult ResetPassword(string id )
        {

            return View(new ResetPasswordVm()
            {
                ActiveCode = id,
            });
        }

        [HttpPost]
        public IActionResult ResetPassword(ResetPasswordVm reset)
        {
            if (!ModelState.IsValid)
            {
                return View(reset);
            }

            User user = _userService.GetUserByActiveCode(reset);
            if(user == null)
            {
                return NotFound();
            }

            user.Password = PasswordHashC.EncodePasswordMd5(reset.Password);
            _userService.Update(user);

            return RedirectToAction("SignIn");
        }


        #endregion
    }
}

MehrCodeLandV1/Areas/UserPannel/Views/UserPannelHome/Index.cshtml
@using Core.Convertor
@using Core.DTOs
@model UserInformationsVm
@{
    ViewData["Title"] = "Dear Pannel " + User.Identity.Name;
    Layout = null;
}

<h1>User Pannel @User.Identity.Name </h1>

<ul>
    <li>@Model.UserName</li>
    <li>@Model.Email</li>
    <li>@Model.Wallet</li>
    <li>@Model.RegisterDate.ToShamsi()</li>
</ul>

MehrCodeLandV1/Areas/Users/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MehrCodeLandV1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MehrCodeLandV1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MehrCodeLandV1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MehrCodeLandV1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MehrCodeLandV1/Areas/Users/Views/UserHome/ActiveUser.cshtml
@{
    Layout = null;
}

@if(ViewBag.IsActived)
{
    <div class="alert alert-success">
        <p>Your Account Is Active Now</p>
        <button type="button">
            <a asp-area="Users" asp-controller="UserHome" asp-action="SignIn">
                SignIn
            </a>
        </button>
    </div>
}else
{
    <div class="alert alert-danger">
        <P>Somthings Wrong</P>
    </div>
}

MehrCodeLandV1/Areas/Users/Views/UserHome/ForgotPassword.cshtml
@using Core.DTOs
@model ForgotPasswordVm
@{
    Layout = null;
}

<h2>Forgot Password</h2>

<div class="form-layer">

    <form asp-action="ForgotPassword" method="post">

        <div class="input-group">
            <span class="input-group-addon" id="email-address"><i class="zmdi zmdi-email"></i></span>
            <input asp-for="Email" type="text" class="form-control" placeholder="Email" aria-describedby="email-address">

        </div>
        <span asp-validation-for="Email"></span>
        <button class="btn btn-success">Send Me Email!</button>

    </form>
</div>

MehrCodeLandV1/Areas/Users/Views/UserHome/Hello.cshtml
@{
    Layout = null;
}
<h2>Hello</h2>

MehrCodeLandV1/Areas/Users/Views/UserHome/Index.cshtml
@{
    Layout = null;
}
<h2>Hello My Friends</h2>


<button type="button">
    <a asp-area="Users" asp-controller="UserHome" asp-action="SignUp">SignUp</a>
</button>
<button type="button">
    <a asp-area="Users" asp-controller="UserHome" asp-action="SignIn">SignIn</a>
</button>

MehrCodeLandV1/Areas/Users/Views/UserHome/ResetPassword.cshtml
@using Core.DTOs
@model ResetPasswordVm
@{
    Layout = null;
}
<h2>Reset Password</h2>

<form  asp-area="Users" asp-controller="UserHome" asp-action="ResetPassword" method="post">

    <input type="hidden" asp-for="ActiveCode" />

    <div class="input-group">
        <span class="input-group-addon" id="password"><i class="zmdi zmdi-lock"></i></span>
        <input asp-for="Password" type="password" class="form-control" placeholder="Password" aria-describedby="password">
    </div>

    <div class="input-group">
        <span class="input-group-addon" id="password"><i class="zmdi zmdi-lock"></i></span>
        <input asp-for="RePassword" type="password" class="form-control" placeholder="RePassword" aria-describedby="password">
    </div>


    <div asp-validation-summary="All" class="text-danger">
    </div>
    <button class="btn btn-success">Password</button>

</form>

MehrCodeLandV1/Areas/Users/Views/UserHome/SignIn.cshtml
@using Core.DTOs
@model SignInViewModel
@{
    Layout = null;
}

<h2>SignIn</h2>
@if(ViewBag.IsSuccess != null){
    <h2>
        <a asp-area="UserPannel" asp-controller="UserPannelHome" asp-action="Index">
            Your Pannel
        </a>
    </h2>
}
<form asp-area="Users" asp-controller="UserHome" asp-action="SignIn">
    <div class="input-group">
        <span class="input-group-addon" id= "username"></span>
        <input asp-for="EmailOrUsername" type="text" class="form-control" placeholder="Username" />
    </div>
    <div class="input-group">
        <span class="input-group-addon" id="password"></span>
        <input asp-for="Password" type="password" class="form-control" placeholder="Password" />
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <button type="submit" class="btn btn-success">SignIn!</button>
    <button type="button">
        <a asp-area="Users" asp-controller="UserHome" asp-action="SignIn">
            I Dont have An Account :) SignUp
        </a>
    </button>
    <button type="button">
        <a asp-area="Users" asp-controller="UserHome" asp-action="ForgotPassword">
            Forgot Password
        </a>
    </button>
    <button type="button">
        <a asp-area="Users" asp-controller="UserHome" asp-action="Hello">
            Hello
        </a>
    </button>
</form>

MehrCodeLandV1/Areas/Users/Views/UserHome/SignUp.cshtml
@using Core.DTOs
@model SignUpViewModel
@{
    Layout = null;
}

<h2>SignUp Page</h2>
<form asp-area="Users" asp-controller="UserHome" asp-action="SignUp">
    <div class="input-group">
        <span class="input-group-addon" id= "username"></span>
        <input asp-for="Usernmae" type="text" class="form-control" placeholder="Username" />
    </div>
    <div class="input-group">
        <span class="input-group-addon" id="email"></span>
        <input asp-for="Email" type="text" class="form-control" placeholder="Email" />
    </div>
    <div class="input-group">
        <span class="input-group-addon" id="password"></span>
        <input asp-for="Password" type="password" class="form-control" placeholder="Password" />
    </div>
    <div class="input-group">
        <span class="input-group-addon" id="repassword"></span>
        <input asp-for="RePassword" type="password" class="form-control" placeholder="Password" />
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <button type="submit" class="btn btn-success">SignUp!</button>
    <button type="button">
        <a asp-area="Users" asp-controller="UserHome" asp-action="SignIn">
            I have Account :) SignIn
        </a>
    </button>
</form>

MehrCodeLandV1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MehrCodeLandV1/Views/Shared/ForgotView.cshtml
@using Data.Entities
@model User
<div style="direction: rtl; padding: 20px">
    <h2> Deare @Model.Username</h2>
    <p>
        Please Reset Your Password !
    </p>
    <p>
        <a href="https://localhost:7195/Users/UserHome/ResetPassword/@Model.ActiveCode">Reset Your Password Now!</a>
    </p>
</div>

MehrCodeLandV1/Views/Shared/Register.cshtml
@using Data.Entities
@model User
<div style="direction: rtl; padding: 20px">
    <h2> Deare @Model.Username</h2>
    <p>
        Please Acctive Your Account
    </p>
    <p>
        <a href="https://localhost:7195/Users/UserHome/ActiveUser/@Model.ActiveCode">Register Now!</a>
    </p>
</div>

MehrCodeLandV1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MehrCodeLandV1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MehrCodeLandV1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MehrCodeLandV1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MehrCodeLandV1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>